FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN mkdir -p data
COPY processed_blogs.json ./data/

EXPOSE 5000

CMD ["python", "app.py"]
